package com.gas.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Data;

@TableName(value ="role_menu_permissions")
@Data
public class RoleMenuPermissions {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu_permissions.role_id
     *
     * @mbggenerated
     */
    @TableId(type = IdType.AUTO)
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu_permissions.menu_permission_id
     *
     * @mbggenerated
     */
    private Integer menuPermissionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_menu_permissions.role_id
     *
     * @return the value of role_menu_permissions.role_id
     *
     * @mbggenerated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_menu_permissions.role_id
     *
     * @param roleId the value for role_menu_permissions.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_menu_permissions.menu_permission_id
     *
     * @return the value of role_menu_permissions.menu_permission_id
     *
     * @mbggenerated
     */
    public Integer getMenuPermissionId() {
        return menuPermissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_menu_permissions.menu_permission_id
     *
     * @param menuPermissionId the value for role_menu_permissions.menu_permission_id
     *
     * @mbggenerated
     */
    public void setMenuPermissionId(Integer menuPermissionId) {
        this.menuPermissionId = menuPermissionId;
    }
}