package com.gas.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Data;

@TableName(value ="role_menu_permissions")
@Data
public class RoleMenuPermissions {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu_permissions.role_id
     *
     * @mbggenerated
     */
    @TableId(type = IdType.AUTO)
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu_permissions.menu_permission_id
     *
     * @mbggenerated
     */
    private Integer menuPermissionId;
}